# Generated by Django 4.1 on 2022-09-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=50)),
                ('fecha_nac', models.DateField()),
                ('domicilio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('id_tipo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField()),
                ('id_material', models.IntegerField()),
                ('fecha_alqu', models.DateField()),
                ('hora_alq', models.DateField()),
                ('fecha_dev_est', models.DateField()),
                ('hora_dev_est', models.DateField()),
                ('recargo', models.BooleanField()),
                ('devuelto', models.BooleanField()),
                ('pagado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
