# Generated by Django 4.1 on 2022-09-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_final', '0002_rents_importe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='fecha_nac',
            field=models.DateField(null=True),
        ),
    ]
