# Generated by Django 4.1 on 2022-09-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_final', '0003_alter_clientes_fecha_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='id_tipo',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
