# Generated by Django 4.1 on 2022-09-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_final', '0004_alter_material_id_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='id_tipo',
            field=models.IntegerField(null=True),
        ),
    ]
