# Generated by Django 4.1 on 2022-09-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_final', '0006_alter_clientes_fecha_nac_alter_material_id_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rents',
            old_name='fecha_alqu',
            new_name='fecha_alq',
        ),
    ]
