# Generated by Django 4.1 on 2022-09-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_final', '0007_rename_fecha_alqu_rents_fecha_alq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rents',
            name='devuelto',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rents',
            name='pagado',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rents',
            name='recargo',
            field=models.BooleanField(null=True),
        ),
    ]
