# Generated by Django 4.1 on 2022-09-14 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t_final', '0008_alter_rents_devuelto_alter_rents_pagado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_final.tipo'),
        ),
        migrations.AlterField(
            model_name='rents',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_final.clientes'),
        ),
        migrations.AlterField(
            model_name='rents',
            name='id_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_final.material'),
        ),
    ]
