# Generated by Django 4.1 on 2022-09-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t_final', '0011_alter_material_id_tipo_alter_rents_id_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='id_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_final.tipo'),
        ),
        migrations.AlterField(
            model_name='rents',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_final.clientes'),
        ),
        migrations.AlterField(
            model_name='rents',
            name='id_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_final.material'),
        ),
    ]
