# Generated by Django 4.1 on 2022-09-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_final', '0013_alter_rents_hora_alq_alter_rents_hora_dev_est'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rents',
            name='devuelto',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rents',
            name='importe',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rents',
            name='pagado',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rents',
            name='recargo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
