# Generated by Django 4.1 on 2022-10-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_final', '0014_alter_rents_devuelto_alter_rents_importe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='activo',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='activo',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='tipo',
            name='activo',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
