# Generated by Django 4.1 on 2022-10-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_final', '0016_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='permiso',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
